fees/urls.py
from django.urls import path
from . import views



urlpatterns = [

    path('dashboard/', views.dashboard, name='dashboard'),
    path('add/', views.addfees, name='addfees'),
    path('recorded/', views.recorded, name='recorded'),
    path('agreement/', views.agreement, name='agreement'),
]

smart_mfis/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginuser, name='home'),
    # path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('profile/', views.profile, name='profile'),
    path('fee/', include('fees.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='student/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='student/password_change.html'),
        name='password_change'),
    # path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
    #  name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #  name='password_reset_complete'),
]

student/models.py
from django.db import models
from django.contrib.auth.models import (
AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.db.models import Sum
from datetime import date

class Grade(models.Model):
    name = models.CharField(max_length=24, blank=True)
    def __str__(self):
        return self.name

class StudentManager(BaseUserManager):
    def create_user(self, code, username, password=None):
        if not code:
            raise ValueError("Users must have a code")
        if not username:
            raise ValueError("Users must have a name")
        user = self.model(
               code = code,
               username = username,
            )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, code, username, password):
        user = self.create_user(
               code = code,
               password = password,
               username = username,
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Student(AbstractBaseUser, PermissionsMixin):
    SCHOOL_CHOICES = (
        (None, ""),
        ('بنين', 'بنين'),
        ('بنات', 'بنات'),
    )
    GRADE_CHOICES = (
        (None, ""),
        ('ثانية حضانة', 'ثانية حضانة'),
        ('الاول الابتدائى','الاول الابتدائى'),
        ('الثانى الابتدائى','الثانى الابتدائى'),
        ('الثالث الابتدائى','الثالث الابتدائى'),
        ('الرابع الابتدائى','الرابع الابتدائى'),
        ('الخامس الابتدائى','الخامس الابتدائى'),
        ('السادس الابتدائى','السادس الابتدائى'),
        ('الاول الاعدادى','الاول الاعدادى'),
        ('الثانى الاعدادى','الثانى الاعدادى'),
        ('الثالث الاعدادى','الثالث الاعدادى'),
        ('الاول الثانوى','الاول الثانوى'),
        ('الثانى الثانوى','الثانى الثانوى'),
        ('الثالث الثانوى','الثالث الثانوى'),
    )
    AREA_CHOICES = (
        (None, ""),
        ('النزهة الجديدة','النزهة الجديدة'),
        ('شيراتون','شيراتون'),
        ('مصر الجديدة','مصر الجديدة'),
        ('الزيتون','الزيتون'),
        ('حدائق القبة','حدائق القبة'),
        ('العباسية','العباسية'),
        ('مدينة نصر','مدينة نصر'),
        ('إمتداد رمسيس','إمتداد رمسيس'),
        ('المعادى','المعادى'),
        ('المقطم','المقطم'),
        ('مدينتى','مدينتى'),
        ('الرحاب','الرحاب'),
        ('التجمع الاول','التجمع الاول'),
        ('التجمع الثالث','التجمع الثالث'),
        ('التجمع الخامس','التجمع الخامس'),

    )

    code = models.CharField(max_length=7, unique=True)
    username = models.CharField(max_length=36,verbose_name='student name')
    school = models.CharField( max_length=4, choices=SCHOOL_CHOICES, blank=True)
    grade = models.CharField( max_length=16, choices=GRADE_CHOICES, blank=True)
    father_mobile = models.CharField(max_length=11, blank=True)
    mother_mobile = models.CharField(max_length=11, blank=True)
    phone_number = models.CharField(max_length=8, blank=True)
    email = models.EmailField(max_length=60, blank=True)

    study_payment1 = models.PositiveSmallIntegerField(default=0)
    study_payment3 = models.PositiveSmallIntegerField(default=0)

    bus_active = models.BooleanField( default=False)
    bus_payment2 = models.PositiveSmallIntegerField( default=0)
    total_paid = models.PositiveSmallIntegerField( default=0)
    def payment_status(self):
#due date 1st study and 1st bus
        if date.today() <= date(2020,9,30):
            if self.bus_active == True:
                return self.study_payment1 + 5000 - self.total_paid
            else:
                return self.study_payment1 - self.total_paid
#due date 1st study and ( 1st ,2nd ) bus payemnts
        elif date.today() <= date(2020,10,31):
            if self.bus_active == True:
                return self.study_payment1 + 5000 + self.bus_payment2 - self.total_paid
            else:
                return self.study_payment1 - self.total_paid
#due date (1st , 2nd) study and ( 1st ,2nd ) bus payemnts
        elif date.today() <= date(2020,12,31):
            if self.bus_active == True:
                return self.study_payment1 + 7000 + 5000 + self.bus_payment2 - self.total_paid
            else:
                return self.study_payment1 + 7000 - self.total_paid
#due date (1st , 2nd ,3rd) study and ( 1st ,2nd ) bus payemnts
        elif date.today() >= date(2021,1,1):
            if self.bus_active == True:
                return self.study_payment1 + 7000 + self.study_payment3 + 5000 + self.bus_payment2 - self.total_paid
            else:
                return self.study_payment1 + 7000 + self.study_payment3 - self.total_paid

    payment_status

    living_area = models.CharField( max_length=16, choices=AREA_CHOICES, blank=True)
    address = models.CharField( max_length=50, blank=True)
    old_bus = models.CharField( max_length=4, blank=True)
    message = models.CharField(max_length=260, null=True, blank=True)

    is_active = models.BooleanField(default=True)
    can_pay = models.BooleanField(default=True)
    is_admin  = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    # is_superuser = models.BooleanField(default=False)
    # is_superuser field provided by PermissionsMixin
    # groups field provided by PermissionsMixin
    # user_permissions field provided by PermissionsMixin

    objects = StudentManager()

    USERNAME_FIELD = 'code'
    REQUIRED_FIELDS = ['username',]


    def __str__(self):
        return self.username + " " + self.code
    # # def __str__(self):
    # #     return self.code
    #
    #
    def has_perm(self, perm, obj=None):
        return self.is_admin
        # return True

    def has_module_perms(self, app_label):
        return True

student/forms.py
from django.forms import ModelForm
from django import forms
from .models import Student



class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['old_bus', 'living_area','address']

#
class StudentProfile(ModelForm):
    class Meta:
        model = Student
        fields = ['father_mobile', 'mother_mobile', 'phone_number', 'email']
#
class StudentArea(ModelForm):
    class Meta:
        model = Student
        fields = ['old_bus', 'living_area', 'address']

student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
# from fees.models import Fees
from django.db.models import Sum
from .forms import StudentProfile

def loginuser(request):
    if request.method == 'GET':
        return render(request, 'student/home.html', {'form':AuthenticationForm})
    else:
        user = authenticate(request, code=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request, 'student/home.html', {'form':AuthenticationForm, 'error':'برجاء التأكد من الكود وكلمة المرور'})
        else:
            login(request, user)
            if user.father_mobile == "":
                return redirect('profile')
            else:
                return redirect('dashboard')

# def home(request):
#     return render(request, 'student/home.html')

def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

def profile(request):
        if request.method == 'GET':
            if request.user.father_mobile == "":
                return render(request, 'student/profile.html', {'form':StudentProfile(), 'error':'برجاء تحديث بيانات التواصل'})
            else:
                return render(request, 'student/profile.html', {'form':StudentProfile()})

        else:
            # add try: except to solve value Error
            try:
                # get the information from the post request and connect it with our form
                # form = StudentProfile(request.POST)
                # Create newtodo but dont't save it yet to the database
                # profile = form.save(commit=False)
                # set the user to newtodo
                # profile.student = request.user
                # newfee.grade = request.user.grade
                # newfee.school = request.user.school
                # save newtodo
                # newfee.save()
                # update student data
                request.user.father_mobile = request.POST['father_mobile']
                request.user.mother_mobile = request.POST['mother_mobile']
                request.user.phone_number = request.POST['phone_number']
                request.user.email = request.POST['email']
                request.user.save(update_fields=["father_mobile", "mother_mobile", "phone_number", "email"])
                # redirect user to currenttodos page
                return redirect('dashboard')
            except ValueError:
                    # tell user when error hapen
                    return render(request, 'student/profile.html', {'form':StudentProfile(),'error':'برجاء مراجعة البيانات'})

student/templates/student/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>MFIS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
    <style media="screen">
    .bg {
      /* The image used */

      /* Full height */
      height: 100%;

      /* Center and scale the image nicely */
      background-position: center;
      background-repeat: no-repeat;
    }
    /* @font-face {
      font-family: 'Tajawal';
      src:url('{% static '/fonts/Tajawal-Regular.ttf' %}') format("truetype"),
          local('Tajawal');
    }
    body{
      font-family: 'Tajawal', sans-serif;
    } */
    @media (max-width:992px){
      .bg {background-image: url("{% static '/images/hero_area_background_tablet_trans.fb7f19816cec.png' %}");
      background-size:cover;}
    }
    @media (max-width:767px){
      .bg {background-image: url("{% static '/images/hero_area_background_mobile_trans.e02b2097cd38.png' %}");
      background-size:cover;}
    }


    </style>
  </head>
  <body>
    {% include 'student/navbar.html' %}
    <div class="bg">{% block content %} {% endblock %}</div>






    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

student/templates/student/home.html
{% extends "student/base.html" %}

{% block content %}
  <div class="container-fluid text-right  ">
    <br>
    <br>
    <br>
    <br>
    <!-- <div class="row justify-content-center mt-5">
        <div class="col-md-5 text-center">
            <h5>تسجيل الدخول</h5>
        </div>
    </div> -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST" class="form-signin">
                {% csrf_token %}
                <!-- <div class="form-group"> -->
                    <!-- <label for="username">: كود الطالب</label> -->
                    <input type="text" name="username" class="form-control" maxlength="7" placeholder="كود الطالب"id="username">
                <!-- </div> -->
                <!-- <div class="form-group"> -->
                    <!-- <label for="password">: كلمة المرور</label> -->
                    <br>
                    <input type="password" name="password" class="form-control" placeholder="كلمة المرور" id="password">
                <!-- </div> -->
                <br>
                <button type="submit" class="btn btn-block ml-0 btn-primary cib ">تسجيل الدخول</button>
            </form>
        </div>
    </div>

  </div>


{% endblock %}

student/templates/student/loginuser.html
{% extends "student/base.html" %}

{% block content %}
  <div class="container-fluid text-right bg-light ">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <!-- <div class="row justify-content-center mt-5">
        <div class="col-md-5 text-center">
            <h5>تسجيل الدخول</h5>
        </div>
    </div> -->
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">: كود الطالب</label>
                    <input type="text" name="username" class="form-control" maxlength="7" id="username">
                </div>
                <div class="form-group">
                    <label for="password">: كلمة المرور</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <br>
                <button type="submit" class="btn ml-0 btn-primary cib ">تسجيل الدخول</button>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
  </div>


{% endblock %}

student/templates/student/navbar.html
{% load static %}
    <nav class="navbar  p-1 navbar-expand-md cib navbar-dark sticky-top ">
      <a href="#" class=" m-0"><img src="{% static '/images/logo.png '%}" height="70" alt="MFIS"></a>
      <a class="navbar-brand m-0 ml-1" href="#">منارة الفاروق الإسلامية للغات</a>
      <button class="navbar-toggler navbar-toggler-right mr-1" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div id="navb" class="navbar-collapse collapse hide text-right">
        <ul class="navbar-nav ml-auto mr-2">
                {% url 'profile' as profile_url1 %}
                {% if user.is_authenticated %}
                {% if request.get_full_path != profile_url1 or  request.get_full_path == profile_url1 and user.father_mobile != "" %}
                <li class="nav-item">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'dashboard' %}">إستعلام مصروفات</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'recorded' %}">مصروفات مسجلة</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'agreement' %}">إشتراك السيارة</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">الملف الشخصي</a>
                  </li>
                  <li class="nav-item">
                      <a href="#" onclick="$('#signOutBtn').click()" class="nav-link"><i class="fa fa-sign-out mr-2"></i>خروج</a>
                      <form style='display: none;' method="POST" action="{% url 'logoutuser' %}">
                          {% csrf_token %}
                          <button id="signOutBtn" type="submit">  تسجيل خروج  </button>
                      </form>
                  </li>
                  {% endif %}
                  {% endif %}
        </ul>
      </div>
    </nav>

student/templates/student/password_change.html
{% extends 'student/base.html' %}

{% block content %}
<!-- <style type="text/css">



</style> -->

<br>
<br>
<form method="POST" class="form-signin text-right">{% csrf_token %}
  <!-- <h4 class=" mb-3 font-weight-normal">تغير كلمة المرور</h4> -->
    <br>
    <input name="old_password" class="form-control" placeholder="كلمة المرور القديمة" type="password" id="id_old_password" required="true">
    <input name="new_password1" class="form-control" placeholder="كلمة المرور الجديدة" type="password" id="id_new_password1" required="true">
    <input name="new_password2" class="form-control" placeholder="تأكيد كلمة المرور" type="password" id="id_new_password2" required="true">

    {% for field in form %}
      {% for error in field.errors %}
        <p style="color: red;text-align: left; ">{{ error }}</p>
      {% endfor %}
    {% endfor %}

  <button class="btn btn-lg btn-primary btn-block cib mt-3" type="submit">تغيير</button>
</form>



{% endblock %}

student/templates/student/password_change_done.html
{% extends 'student/base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<div class="container">
	<div class="d-flex flex-column">
		<h6 class="m-auto">لقد تم تغير كلمة المرور بنجاح</h6>
	</div>
</div>

{% endblock %}

student/templates/student/profile.html
{% extends "student/base.html" %}

{% block content %}

  <div class="container-fluid text-right  ">
    <br>
    <br>
    {% if error %}
    <div class="row">
        <div class="col-md-7">
        </div>
        <div class="col-md-5">
            <div class="card text-right border-black ">
                <h6 class="card-header">
          {% if user.school == "بنين" %}
           مرحباً بالطالب
          {% else %}
           مرحباً بالطالبة
          {% endif %}
                </h6>
                <div class="card-body ">
                    <h6 class="card-text">
                        {{ user.username }}
                    </h6>
                </div>
                <div class="card-footer ">
            {{ user.get_grade_display }} - {{ user.school }}
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}
    <div class="row justify-content-center mt-4">
        <div class="col-md-5">

            <form method="POST" class="form-signin">
                {% csrf_token %}

                    <input type="text" name="father_mobile" class="form-control mb-3" placeholder="هاتف الأب" required="" maxlength="11" id="id_father_mobile">                  
                    <input type="text" name="mother_mobile" class="form-control mb-3" placeholder="هاتف الأم" required="" maxlength="11" id="id_mother_mobile">
                    <input type="text" name="phone_number" class="form-control mb-3" placeholder="هاتف المنزل" maxlength="8" id="id_phone_number">
                    <input type="email" name="email" class="form-control mb-3" placeholder="البريد الإلكتروني" required="" maxlength="60" id="id_email">
            {% if user.father_mobile != "" %}
                <div>
                    <a class="text-left" href="{% url 'password_change' %}">تغير كلمة المرور</a>
                </div>
            {% endif %}
                <button type="submit" class="btn btn-block mt-4 btn-primary cib ">حفظ البيانات</button>

            </form>
        </div>
    </div>
  </div>


{% endblock %}