fees/urls.py
from django.urls import path
from . import views



urlpatterns = [

    path('dashboard/', views.dashboard, name='dashboard'),
    path('add/', views.addfees, name='addfees'),
    path('recorded/', views.recorded, name='recorded'),
    path('agreement/', views.agreement, name='agreement'),
]

smart_mfis/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.loginuser, name='home'),
    # path('login/', views.loginuser, name='loginuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('profile/', views.profile, name='profile'),
    path('fee/', include('fees.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='student/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='student/password_change.html'),
        name='password_change'),
    # path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
    #  name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
    #  name='password_reset_complete'),
]

fees/models.py
from django.db import models
# from account.models import Account

class Fee(models.Model):
    BankA_CHOICES = (
        ('نقدي بالمدرسة', 'نقدي بالمدرسة'),
        ('1903530354880500015', '1903530354880500015'),
        ('1903530635939400011', '1903530635939400011'),
        ('1903530776181400019', '1903530776181400019'),
        ('1903530635939300017', '1903530635939300017'),
        ('1903530709961400015', '1903530709961400015'),
    )

    KIND_CHOICES = (
        ('دراسية', 'دراسية'),
        ('سيارة', 'سيارة'),
    )

    SCHOOL_CHOICES = (
        (None, ""),
        ('بنين', 'بنين'),
        ('بنات', 'بنات'),
    )

    payment_date = models.DateField(null=True, blank=True)
    bank_account = models.CharField(max_length=19, choices=BankA_CHOICES)
    value = models.PositiveSmallIntegerField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    kind = models.CharField(max_length=6, choices=KIND_CHOICES)
    school = models.CharField( max_length=4, choices=SCHOOL_CHOICES, blank=True)
    student = models.ForeignKey(to='student.Student', on_delete=models.CASCADE, null=True)


    def __str__(self):
        return self.student.username

student/models.py
from django.db import models
from django.contrib.auth.models import (
AbstractBaseUser, BaseUserManager, PermissionsMixin
)
from django.db.models import Sum
from datetime import date

class Grade(models.Model):
    name = models.CharField(max_length=24, blank=True)
    def __str__(self):
        return self.name

class StudentManager(BaseUserManager):
    def create_user(self, code, username, password=None):
        if not code:
            raise ValueError("Users must have a code")
        if not username:
            raise ValueError("Users must have a name")
        user = self.model(
               code = code,
               username = username,
            )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, code, username, password):
        user = self.create_user(
               code = code,
               password = password,
               username = username,
            )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class Student(AbstractBaseUser, PermissionsMixin):
    SCHOOL_CHOICES = (
        (None, ""),
        ('بنين', 'بنين'),
        ('بنات', 'بنات'),
    )
    GRADE_CHOICES = (
        (None, ""),
        ('ثانية حضانة', 'ثانية حضانة'),
        ('الاول الابتدائى','الاول الابتدائى'),
        ('الثانى الابتدائى','الثانى الابتدائى'),
        ('الثالث الابتدائى','الثالث الابتدائى'),
        ('الرابع الابتدائى','الرابع الابتدائى'),
        ('الخامس الابتدائى','الخامس الابتدائى'),
        ('السادس الابتدائى','السادس الابتدائى'),
        ('الاول الاعدادى','الاول الاعدادى'),
        ('الثانى الاعدادى','الثانى الاعدادى'),
        ('الثالث الاعدادى','الثالث الاعدادى'),
        ('الاول الثانوى','الاول الثانوى'),
        ('الثانى الثانوى','الثانى الثانوى'),
        ('الثالث الثانوى','الثالث الثانوى'),
    )
    AREA_CHOICES = (
        (None, ""),
        ('النزهة الجديدة','النزهة الجديدة'),
        ('شيراتون','شيراتون'),
        ('مصر الجديدة','مصر الجديدة'),
        ('الزيتون','الزيتون'),
        ('حدائق القبة','حدائق القبة'),
        ('العباسية','العباسية'),
        ('مدينة نصر','مدينة نصر'),
        ('إمتداد رمسيس','إمتداد رمسيس'),
        ('المعادى','المعادى'),
        ('المقطم','المقطم'),
        ('مدينتى','مدينتى'),
        ('الرحاب','الرحاب'),
        ('التجمع الاول','التجمع الاول'),
        ('التجمع الثالث','التجمع الثالث'),
        ('التجمع الخامس','التجمع الخامس'),

    )

    code = models.CharField(max_length=7, unique=True)
    username = models.CharField(max_length=36,verbose_name='student name')
    school = models.CharField( max_length=4, choices=SCHOOL_CHOICES, blank=True)
    grade = models.CharField( max_length=16, choices=GRADE_CHOICES, blank=True)
    father_mobile = models.CharField(max_length=11, blank=True)
    mother_mobile = models.CharField(max_length=11, blank=True)
    phone_number = models.CharField(max_length=8, blank=True)
    email = models.EmailField(max_length=60, blank=True)

    study_payment1 = models.PositiveSmallIntegerField(default=0)
    study_payment3 = models.PositiveSmallIntegerField(default=0)

    bus_active = models.BooleanField( default=False)
    bus_payment2 = models.PositiveSmallIntegerField( default=0)
    total_paid = models.PositiveSmallIntegerField( default=0)
    def payment_status(self):
#due date 1st study and 1st bus
        if date.today() <= date(2020,9,30):
            if self.bus_active == True:
                return self.study_payment1 + 5000 - self.total_paid
            else:
                return self.study_payment1 - self.total_paid
#due date 1st study and ( 1st ,2nd ) bus payemnts
        elif date.today() <= date(2020,10,31):
            if self.bus_active == True:
                return self.study_payment1 + 5000 + self.bus_payment2 - self.total_paid
            else:
                return self.study_payment1 - self.total_paid
#due date (1st , 2nd) study and ( 1st ,2nd ) bus payemnts
        elif date.today() <= date(2020,12,31):
            if self.bus_active == True:
                return self.study_payment1 + 7000 + 5000 + self.bus_payment2 - self.total_paid
            else:
                return self.study_payment1 + 7000 - self.total_paid
#due date (1st , 2nd ,3rd) study and ( 1st ,2nd ) bus payemnts
        elif date.today() >= date(2021,1,1):
            if self.bus_active == True:
                return self.study_payment1 + 7000 + self.study_payment3 + 5000 + self.bus_payment2 - self.total_paid
            else:
                return self.study_payment1 + 7000 + self.study_payment3 - self.total_paid

    payment_status

    living_area = models.CharField( max_length=16, choices=AREA_CHOICES, blank=True)
    address = models.CharField( max_length=50, blank=True)
    old_bus = models.CharField( max_length=4, blank=True)
    message = models.CharField(max_length=260, null=True, blank=True)

    is_active = models.BooleanField(default=True)
    can_pay = models.BooleanField(default=True)
    is_admin  = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    # is_superuser = models.BooleanField(default=False)
    # is_superuser field provided by PermissionsMixin
    # groups field provided by PermissionsMixin
    # user_permissions field provided by PermissionsMixin

    objects = StudentManager()

    USERNAME_FIELD = 'code'
    REQUIRED_FIELDS = ['username',]


    def __str__(self):
        return self.username + " " + self.code
    # # def __str__(self):
    # #     return self.code
    #
    #
    def has_perm(self, perm, obj=None):
        return self.is_admin
        # return True

    def has_module_perms(self, app_label):
        return True

fees/forms.py
from django.forms import ModelForm
from django import forms
from .models import Fee

class DateInput(forms.DateInput):
    input_type = 'date'

class FeesForm(ModelForm):
    class Meta:
        model = Fee
        fields = ['kind', 'payment_date', 'bank_account','value']
    payment_date = forms.DateField(widget=DateInput)

fees/views.py
from django.shortcuts import render, redirect, reverse
from .forms import FeesForm
from .models import Fee
from student.forms import StudentForm, StudentArea
# from django.contrib.auth import authenticate, login

def dashboard(request):
    # ddate1=DueDates.objects.get(pk=1)
    # ddate2=DueDates.objects.get(pk=2)
    # feess = Fees.objects.filter(student=request.user)
    student=request.user
    # fees = student.fee_set.all()
    #totalfees = feess.aggregate(Sum('value'))

    return render(request, 'fees/dashboard.html')

def addfees(request):
    if request.method == 'GET':
        # feess = Fees.objects.filter(student=request.user.id)
        return render(request, 'fees/addfees.html', {'form':FeesForm()})
    else:
        if request.user.can_pay == True:
            if request.POST['kind'] == "دراسية":
                # add try: except to solve value Error
                try:
                    # get the information from the post request and connect it with our form
                    form = FeesForm(request.POST)
                    # Create newtodo but dont't save it yet to the database
                    newfee = form.save(commit=False)
                    # set the user to newtodo
                    newfee.student = request.user
                    # newfee.grade = request.user.grade
                    newfee.school = request.user.school
                    # save newtodo
                    newfee.save()
                    # update student data
                    request.user.total_paid += int(request.POST['value'])
                    request.user.save(update_fields=["total_paid"])
                    # redirect user to currenttodos page
                    return redirect('dashboard')
                except ValueError:
                        # tell user when error hapen
                        return render(request, 'fees/addfees.html', {'form':FeesForm(),'error':'برجاء مراجعة البيانات'})
            else:
                if request.user.bus_active == True:
                    # add try: except to solve value Error
                    try:
                        # get the information from the post request and connect it with our form
                        form = FeesForm(request.POST)
                        # Create newtodo but dont't save it yet to the database
                        newfee = form.save(commit=False)
                        # set the user to newtodo
                        newfee.student = request.user
                        # newfees.grade = request.user.grade
                        newfee.school = request.user.school
                        # save newtodo
                        newfee.save()
                        # update student data
                        request.user.total_paid += int(request.POST['value'])
                        request.user.save(update_fields=["total_paid"])
                        # redirect user to currenttodos page
                        return redirect('dashboard')
                    except ValueError:
                            # tell user when error hapen
                            return render(request, 'fees/addfees.html', {'form':FeesForm(),'error':'برجاء مراجعة البيانات'})
                else:
                    error = 'لا يمكن تسجيل الايصال قبل الموافقة على تعليمات السيارة وتحديد المنطقة السكنية في صفحة إشتراك السيارة اولاً'

                    return render(request, 'fees/addfees.html', {'form':FeesForm(),'error':error})

        else:
            return render(request, 'fees/addfees.html', {'form':FeesForm(),'error':'برجاء مراجعة قسم الحسابات'})
def recorded(request):
    fees = Fee.objects.filter(student=request.user.id)
    return render(request, 'fees/recorded.html',{'fees':fees})


def agreement(request):
    if request.method == 'GET':
        return render(request, 'fees/agreement.html', {'form':StudentArea()})
    else:
        if request.user.bus_active == False:
            try:
                # # get the information from the post request and connect it with our form
                # form = AccountForm(request.POST)
                # # Create newtodo but dont't save it yet to the database
                # newfees = form.save(commit=False)
                # # set the user to newtodo
                # newfees.student = request.user
                # newfees.grade = request.user.grade
                # newfees.school = request.user.school
                # # save newtodo
                # newfees.save()
                # update student data
                request.user.bus_active = True
                request.user.old_bus = request.POST['old_bus']
                request.user.living_area = request.POST['living_area']
                request.user.address = request.POST['address']
                request.user.save(update_fields=["bus_active", "old_bus", "living_area", "address"])
                # redirect user to currenttodos page
                return redirect('dashboard')
            except ValueError:
                    # tell user when error hapen
                    return render(request, 'fees/agreement.html', {'form':FeesForm(),'error':'برجاء مراجعة البيانات'})
        else:
            return render(request, 'fees/agreement.html', {'form':FeesForm(),'error':'لتعديل البيانات يجب التواصل مع إدارة تشغيل السيارات'})

fees/templates/fees/addfees.html
{% extends 'student/base.html' %}

{% block content %}

<br>
<div class="container-fluid text-right">
  <div class="row justify-content-center mt-5">
      <div class="col-md-5 ">
          <h5> تسجيل ايصالات الدفع</h5>

      </div>
  </div>
  <div class="row justify-content-center ">
      <div class="col-md-5">
          {% if error %}
              <div class="alert alert-danger" role="alert">
                  {{ error }}
              </div>
          {% endif %}
          <form method="POST" class="form-signin">
              {% csrf_token %}
                  <br>
                  <select dir="rtl" name="kind" required="" class="form-control" id="id_kind">
                    <option value="" selected="">مصروفات</option>
                    <option value="دراسية">دراسية</option>
                    <option value="سيارة">سيارة</option>
                  </select>

                  <br>
                  <input type="number" name="value" min="0" class="form-control" placeholder="القيمة" equired="" id="id_value">
                  <br>
                  <select dir="rtl" name="bank_account" required=""  class="form-control" id="id_bank_account">
                    <option value="" selected="">حساب الدفع</option>
                    <option value="1903530354880500015">1903530354880500015</option>
                    <option value="1903530635939400011">1903530635939400011</option>
                    <option value="1903530776181400019">1903530776181400019</option>
                    <option value="1903530635939300017">1903530635939300017</option>
                    <option value="1903530709961400015">1903530709961400015</option>
                  </select>
                  <br>
                  <input type="text"  name="payment_date" required="" placeholder="تاريخ الدفع بالبنك" onfocus="(this.type='date')"
                  onblur="(this.type='text')" class="form-control" id="id_payment_date">
              <!-- </div> -->
              <br>
              <button type="submit" class="btn btn-primary btn-block cib">تسجيل ايصال الدفع</button>
          </form>

      </div>
  </div>
</div>
<!-- <br>
<br>
<div class="container-fluid ">
  <div class="row ">
    <div class="col-md-8  ">
    </div>
    <div class="col-md-4  text-right">
      <h6>عمليات السداد السابقة</h6>
    </div>
  </div>
  <div class="row "
  <div class="col-md-7 ">
  </div>
    <div class="col-md-5 ml-auto text-center ">
  		<table class="table table-hover">
  		  <thead>
  		    <tr>
  		      <th scope="col">تاريخ التسجيل</th>
            <th scope="col">المبلغ</th>
  		    </tr>
  		  </thead>
  		  <tbody>
           {% for fees in feess %}
  		    <tr>
  		      <td>{{ fees.created }}</td>
            <th scope="row">{{ fees.value }}</th>
           {% endfor %}
  		  </tbody>
  		</table>
    </div>
</div> -->
{% endblock %}

fees/templates/fees/agreement.html
{% extends 'student/base.html' %}

{% block content %}
{% load static %}
<!-- <h2>اتفاقية الاستخدام</h2>
<h5>{{ error }}</h5> -->

<div class="container-fluid  text-right">

  <br>
	<div class="row">
		<div class="col-md-12 ml-auto text-right mt-4">
			<div id="card-434025">
				<div class="card">
					<div class="card-header">
						 <a class="card-link collapsed" data-toggle="collapse" data-parent="#card-434025" href="#card-element-708669">تعليمات الإشتراك في سيارة المدرسة</a>
					</div>
					<div id="card-element-708669" class="collapse">
						<div class="card-body">
								<img src="{% static 'images/agrement-s.jpg'%}" class="img-fluid" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
  </div>
  <div class="row justify-content-center  mt-3">
      <div class="col-md-5">
        {% if error %}
            <div class="alert alert-danger mt-3" role="alert">
                {{ error }}
            </div>
        {% endif %}

          <form method="POST" class="form-signin">
              {% csrf_token %}

                  <br>

                  <select dir="rtl" name="living_area" class="form-control" id="id_living_area" required="">
                    <option value="" selected="">منطقة السكن</option>
                    <option value="النزهة الجديدة">النزهة الجديدة</option>
                    <option value="شيراتون">شيراتون</option>
                    <option value="مصر الجديدة">مصر الجديدة</option>
                    <option value="الزيتون">الزيتون</option>
                    <option value="حدائق القبة">حدائق القبة</option>
                    <option value="العباسية">العباسية</option>
                    <option value="مدينة نصر">مدينة نصر</option>
                    <option value="إمتداد رمسيس">إمتداد رمسيس</option>
                    <option value="المعادى">المعادى</option>
                    <option value="المقطم">المقطم</option>
                    <option value="مدينتى">مدينتى</option>
                    <option value="الرحاب">الرحاب</option>
                    <option value="التجمع الاول">التجمع الاول</option>
                    <option value="التجمع الثالث">التجمع الثالث</option>
                    <option value="التجمع الخامس">التجمع الخامس</option>
                    

                  </select>

                  <br>
                    <input type="text" name="address" class="form-control" placeholder="العنوان" maxlength="50" id="id_address" required="">
              <br>
              <input type="text" name="old_bus" class="form-control" placeholder="كود سيارة العام السابق" maxlength="3" id="id_old_bus">
              <button type="submit" class="btn btn-block btn-primary mt-5 cib">اوافق علي التعليمات</button>

          </form>

      </div>
  </div>
  <br>
  <br>
  <br>
  <br>
</div>
{% endblock %}

fees/templates/fees/recorded.html
{% extends 'student/base.html' %}

{% block content %}


<!-- <div class="container-fluid  text-right">
  <div class="row justify-content-center mt-5"> -->

<div class="container-fluid">



  <br>
  <br>
  <div class="row ">
    <div class="col-md-8  ">
    </div>
    <div class="col-md-4  mb-3 text-right">
      <h6><b>مصروفات مسجلة</b></h6>
    </div>
  </div>

  <div class="row"
  <div class="col-md-7 ">
  </div>
    <div class="col-md-5 ml-auto text-center">
  		<table class="table table-hover">
  		  <thead>
  		    <tr>

  		      <th scope="col">التاريخ</th>
            <th scope="col">المبلغ</th>
            <th scope="col">مصروفات</th>
  		    </tr>
  		  </thead>
  		  <tbody>
           {% for fee in fees %}
  		    <tr>

  		      <td>{{ fee.payment_date }}</td>
            <th scope="row">{{ fee.value }}</th>
            <td>{{ fee.kind }}</td>
           {% endfor %}
  		  </tbody>
  		</table>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
</div>

{% endblock %}